#!/bin/bash

if [[ $1 == "" ]]; then
	echo Please provide a folder to test...
	exit
fi

for file in `ls tests/$1/ | grep in | cut -d"." -f1`; do
	./hw3 < tests/$1/${file}.in > tests/$1/${file}
	DIFF=$(diff tests/$1/${file} tests/$1/${file}.out)
    if [[ "$DIFF" != "" ]]; then
	   	# echo $DIFF
        echo ${file} "failed"
    fi
done
